// ─────────────────────────────────────────────────────────────────────────────
// RIGHTS AGENT — generates professional data-removal / erasure requests
// Uses LLM to write the letter when available; falls back to template
// DISCLAIMER: Not legal advice.
// ─────────────────────────────────────────────────────────────────────────────

import { prisma } from '../../utils/prisma';
import { emitAgentEvent } from '../../utils/socketEmitter';
import { logger } from '../../utils/logger';
import { PrivacyWorkflowState, PrivacyRequestDraft } from '../../types';
import { callOllama } from '../../services/ollamaService';

function templateRequest(
  userName: string,
  targetOrg: string,
  dataTypes: string[],
  riskLevel: string
): string {
  const date = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  const dataList = dataTypes.map((d) => `  • ${d.replace(/_/g, ' ')}`).join('\n');

  return `Date: ${date}

To: The Data Protection / Privacy Team
Organisation: ${targetOrg}

Subject: Formal Request for Erasure of Personal Data — Right to Be Forgotten

Dear Data Protection Officer,

I, ${userName}, formally request the permanent erasure of all personal data held about me by ${targetOrg}, pursuant to applicable data protection regulations including the General Data Protection Regulation (GDPR) and the Digital Personal Data Protection Act 2023 (India).

The following personal data has been identified as exposed or held without my explicit consent:
${dataList}

I request that you:
1. Permanently delete all personal data listed above and any other data held about me.
2. Cease processing, sharing, or selling my personal data to any third party.
3. Confirm in writing within 30 days that erasure is complete.
4. Notify any third parties who received my data of this erasure request.

If processing is based on consent, please provide evidence. If you are unable to comply, please provide the specific legal basis for retention.

Please acknowledge receipt within 72 hours.

Sincerely,
${userName}

---
NOTE: This request was generated by PRIVEX, an autonomous privacy protection tool.
This document is NOT legal advice. For legal proceedings, consult a qualified privacy lawyer.
Risk level at time of request: ${riskLevel}`;
}

export async function rightsAgent(state: PrivacyWorkflowState): Promise<PrivacyWorkflowState> {
  const { userId, scanId, findings, riskResults, userProfile } = state;

  logger.info('RightsAgent started', { scanId });

  emitAgentEvent({
    scanId, agentName: 'RIGHTS', status: 'RUNNING',
    message: 'Rights Agent is preparing data-removal requests for high-risk exposures',
    timestamp: new Date().toISOString(),
  });

  const run = await prisma.agentRun.create({
    data: {
      userId, scanId,
      agentName: 'RIGHTS',
      task: 'Generate professional privacy removal requests for HIGH and CRITICAL exposures',
      status: 'RUNNING',
      startedAt: new Date(),
    },
  });

  try {
    await new Promise((r) => setTimeout(r, 400));

    const privacyRequests: PrivacyRequestDraft[] = [];
    const actionableRisks = riskResults.filter((r) => ['HIGH', 'CRITICAL'].includes(r.riskLevel));

    const exposures = await prisma.exposure.findMany({
      where: { userId, status: 'ACTION_REQUIRED' },
      orderBy: { createdAt: 'asc' },
    });

    for (let i = 0; i < actionableRisks.length; i++) {
      const risk = actionableRisks[i];
      const finding = findings[risk.findingIndex];
      const exposure = exposures[risk.findingIndex] ?? exposures[i];

      if (!finding || !exposure) continue;

      const requestType = finding.dataTypes.includes('password_hash')
        ? 'DATA_DELETION'
        : 'RIGHT_TO_ERASURE';

      const template = templateRequest(
        userProfile.name, finding.source, finding.dataTypes, risk.riskLevel
      );

      // Ask LLM to write a better version of the letter
      const llmPrompt = `You are a privacy rights specialist writing a formal data removal request letter.

Write a professional, firm, and polite GDPR / DPDP Act data erasure request letter on behalf of:
Name: ${userProfile.name}
To organisation: ${finding.source}
Exposed data types: ${finding.dataTypes.join(', ')}
Risk level: ${risk.riskLevel}

The letter must:
- Be formal and professional
- Reference GDPR Article 17 (Right to Erasure) or DPDP Act 2023
- Request deletion of all the listed data types
- Ask for written confirmation within 30 days
- Include a disclaimer that this is not legal advice
- Be between 200-350 words
- Include today's date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}

Write ONLY the letter text, starting with "Date:".`;

      const { text: generatedRequest } = await callOllama(llmPrompt, template);

      const draft: PrivacyRequestDraft = {
        targetOrg: finding.source,
        requestType,
        reason: risk.explanation,
        generatedRequest,
      };

      privacyRequests.push(draft);

      // Check if request already exists for this exposure (from a previous scan)
      const existing = await prisma.privacyRequest.findFirst({
        where: { userId, exposureId: exposure.id, requestType: requestType as any },
      });

      if (!existing) {
        await prisma.privacyRequest.create({
          data: {
            userId,
            exposureId: exposure.id,
            targetOrg: finding.source,
            requestType: requestType as any,
            reason: risk.explanation,
            generatedRequest,
            status: 'READY',
          },
        });
      }
    }

    await prisma.agentRun.update({
      where: { id: run.id },
      data: {
        status: 'COMPLETED',
        result: `${privacyRequests.length} removal requests prepared`,
        metadata: { count: privacyRequests.length },
        completedAt: new Date(),
      },
    });

    emitAgentEvent({
      scanId, agentName: 'RIGHTS', status: 'COMPLETED',
      message: `${privacyRequests.length} privacy removal requests are ready to send`,
      timestamp: new Date().toISOString(),
      metadata: { count: privacyRequests.length },
    });

    return { ...state, privacyRequests, currentStep: 'GUARDIAN' };
  } catch (error) {
    logger.error('RightsAgent failed', { scanId, error });

    await prisma.agentRun.update({
      where: { id: run.id },
      data: { status: 'FAILED', result: 'Rights agent failed', completedAt: new Date() },
    });

    emitAgentEvent({
      scanId, agentName: 'RIGHTS', status: 'FAILED',
      message: 'Rights Agent encountered an error — moving to Guardian',
      timestamp: new Date().toISOString(),
    });

    return { ...state, errors: [...state.errors, 'Rights agent failed'], currentStep: 'GUARDIAN' };
  }
}
