// ─────────────────────────────────────────────────────────────────────────────
// PRIVEX — Demo Seed Script
//
// Creates the demo user "Alex Kumar" and runs a full privacy scan so judges
// can log in immediately and see a pre-populated dashboard.
//
// Usage:
//   npx ts-node src/scripts/seed.ts
//
// Safe to run multiple times — uses upsert so it won't duplicate data.
// ─────────────────────────────────────────────────────────────────────────────

import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
import { PrismaClient } from '@prisma/client';
import { getDemoFindings } from '../tools/demoDataset';

const prisma = new PrismaClient();

const DEMO_EMAIL    = 'alex.kumar@demo.privex';
const DEMO_PASSWORD = 'demo1234';
const DEMO_NAME     = 'Alex Kumar';

// ── Risk scoring (copy of agent logic — no circular dep needed)
function scoreRisk(dataTypes: string[], confidence: number) {
  const types = new Set(dataTypes);
  const factors: string[] = [];
  let score = 0;

  if (types.has('password_hash'))    { score += 40; factors.push('Credential data exposed'); }
  if (types.has('address'))          { score += 25; factors.push('Physical address disclosed'); }
  if (types.has('email'))            { score += 15; factors.push('Email address exposed'); }
  if (types.has('phone'))            { score += 15; factors.push('Phone number exposed'); }
  if (types.has('name'))             { score += 10; factors.push('Full name disclosed'); }
  if (types.has('purchase_history')) { score += 15; factors.push('Purchase behaviour tracked'); }
  if (types.has('demographics'))     { score += 10; factors.push('Demographic profile available'); }
  if (types.has('employer'))         { score +=  8; factors.push('Employer information disclosed'); }
  if (types.has('location'))         { score +=  8; factors.push('Location data available'); }
  if (types.has('username'))         { score +=  5; factors.push('Username exposed'); }
  if (types.size >= 4) { score += 15; factors.push('Multiple identifiers — high correlation risk'); }
  else if (types.size >= 3) { score += 8; factors.push('Cross-referencing risk from 3+ data types'); }

  score = Math.min(100, Math.round(score * confidence));

  type RL = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  let riskLevel: RL;
  let explanation: string;
  let recommendation: string;

  if (score >= 75) {
    riskLevel = 'CRITICAL';
    explanation = `Critical risk. ${factors.join(', ')}. This combination of data could enable identity theft, account takeover, and targeted phishing attacks with very high success probability.`;
    recommendation = 'Submit an urgent data-erasure request immediately and change related passwords.';
  } else if (score >= 50) {
    riskLevel = 'HIGH';
    explanation = `High risk. ${factors.join(', ')}. This data makes you significantly more vulnerable to phishing, spam, and social engineering attacks.`;
    recommendation = 'Request data removal and monitor accounts for suspicious activity.';
  } else if (score >= 25) {
    riskLevel = 'MEDIUM';
    explanation = `Medium risk. ${factors.join(', ')}. This data could be used to build a profile on you or target you with personalised scams.`;
    recommendation = 'Submit an opt-out request to limit further use of your data.';
  } else {
    riskLevel = 'LOW';
    explanation = `Low risk. ${factors.join(', ')}. Limited direct harm but contributes to your overall data footprint.`;
    recommendation = 'Monitor for changes. An opt-out request is optional but recommended.';
  }

  return { riskLevel, riskScore: score, explanation, factors, recommendation };
}

function generateRequest(name: string, org: string, dataTypes: string[], riskLevel: string): string {
  const date = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  return `Date: ${date}

To: The Data Protection / Privacy Team
Organisation: ${org}

Subject: Formal Request for Erasure of Personal Data

Dear Data Protection Officer,

I, ${name}, formally request the permanent erasure of all personal data held about me by ${org}, pursuant to the General Data Protection Regulation (GDPR) and the Digital Personal Data Protection Act 2023 (India).

Exposed data identified:
${dataTypes.map((d) => `  • ${d.replace(/_/g, ' ')}`).join('\n')}

Please:
1. Permanently delete all listed personal data.
2. Cease all processing and sharing of my data.
3. Confirm deletion in writing within 30 days.
4. Notify any third parties of this request.

Risk level: ${riskLevel}

Sincerely,
${name}

---
NOTE: Generated by PRIVEX. This is NOT legal advice.`;
}

async function seed() {
  console.log('\n🌱 PRIVEX Demo Seed Script\n');

  // 1. Upsert demo user
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 12);
  const user = await prisma.user.upsert({
    where: { email: DEMO_EMAIL },
    update: { name: DEMO_NAME, passwordHash },
    create: { email: DEMO_EMAIL, passwordHash, name: DEMO_NAME },
  });
  console.log(`✅ Demo user: ${user.email} (id: ${user.id})`);

  // 2. Clear old demo data for clean re-seed
  await prisma.agentRun.deleteMany({ where: { userId: user.id } });
  await prisma.followUp.deleteMany({ where: { userId: user.id } });
  await prisma.privacyRequest.deleteMany({ where: { userId: user.id } });
  await prisma.verificationResult.deleteMany({ where: { exposure: { userId: user.id } } });
  await prisma.riskAssessment.deleteMany({ where: { exposure: { userId: user.id } } });
  await prisma.exposure.deleteMany({ where: { userId: user.id } });
  console.log('✅ Old demo data cleared');

  const scanId = uuidv4();
  const findings = getDemoFindings();

  // 3. Agent runs
  const agentDefs = [
    { name: 'ORCHESTRATOR', task: 'Plan and coordinate the privacy workflow',
      result: 'Plan created: SCOUT → RISK → RIGHTS → GUARDIAN', delay: 0 },
    { name: 'SCOUT',        task: 'Discover exposed personal information',
      result: `${findings.length} exposures discovered`, delay: 1200 },
    { name: 'RISK',         task: `Analyse ${findings.length} exposures and assign risk levels`,
      result: '2 critical, 2 high-risk exposures identified', delay: 2000 },
    { name: 'RIGHTS',       task: 'Generate removal requests for HIGH and CRITICAL exposures',
      result: '3 removal requests prepared', delay: 2600 },
    { name: 'GUARDIAN',     task: 'Create follow-up schedule and update exposure tracking',
      result: '3 follow-up schedules created', delay: 3100 },
  ];

  for (const def of agentDefs) {
    const start = new Date(Date.now() - (5000 - def.delay));
    const end   = new Date(start.getTime() + 800);
    await prisma.agentRun.create({
      data: {
        userId: user.id, scanId,
        agentName: def.name, task: def.task,
        status: 'COMPLETED', result: def.result,
        startedAt: start, completedAt: end,
      },
    });
  }
  console.log('✅ Agent runs created');

  // 4. Exposures + risk assessments
  const createdExposures: string[] = [];
  for (const finding of findings) {
    const exposure = await prisma.exposure.create({
      data: {
        userId: user.id,
        source: finding.source,
        dataTypes: finding.dataTypes,
        severityCandidate: finding.severityCandidate,
        confidence: finding.confidence,
        evidence: finding.evidence,
        rawData: finding.rawData as any,
        status: 'ACTION_REQUIRED',
      },
    });
    createdExposures.push(exposure.id);

    const risk = scoreRisk(finding.dataTypes, finding.confidence);
    await prisma.riskAssessment.create({
      data: {
        exposureId: exposure.id,
        riskLevel: risk.riskLevel as any,
        riskScore: risk.riskScore,
        explanation: risk.explanation,
        factors: risk.factors,
        recommendation: risk.recommendation,
      },
    });
  }
  console.log(`✅ ${findings.length} exposures + risk assessments created`);

  // 5. Privacy requests for HIGH/CRITICAL
  const requestTargets = findings.filter((f) => {
    const r = scoreRisk(f.dataTypes, f.confidence);
    return ['HIGH', 'CRITICAL'].includes(r.riskLevel);
  });

  for (let i = 0; i < requestTargets.length; i++) {
    const f   = requestTargets[i];
    const r   = scoreRisk(f.dataTypes, f.confidence);
    const req = await prisma.privacyRequest.create({
      data: {
        userId: user.id,
        exposureId: createdExposures[i],
        targetOrg: f.source,
        requestType: f.dataTypes.includes('password_hash') ? 'DATA_DELETION' : 'RIGHT_TO_ERASURE',
        reason: r.explanation,
        generatedRequest: generateRequest(DEMO_NAME, f.source, f.dataTypes, r.riskLevel),
        status: 'READY',
      },
    });

    // Follow-up 14 days out
    const followUpDate = new Date();
    followUpDate.setDate(followUpDate.getDate() + 14);
    await prisma.followUp.create({
      data: {
        userId: user.id,
        privacyRequestId: req.id,
        scheduledAt: followUpDate,
        status: 'PENDING',
        notes: 'Auto-scheduled by Guardian Agent — check if organisation has responded',
      },
    });
  }
  console.log(`✅ ${requestTargets.length} privacy requests + follow-ups created`);

  // 6. One resolved exposure for demo score boost
  await prisma.exposure.update({
    where: { id: createdExposures[5] },
    data: { status: 'RESOLVED', resolvedAt: new Date() },
  });
  await prisma.verificationResult.create({
    data: {
      exposureId: createdExposures[5],
      method: 'manual_check',
      outcome: 'RESOLVED',
      notes: 'Organisation confirmed deletion via email',
    },
  });
  console.log('✅ One exposure marked as resolved');

  console.log('\n🎉 Seed complete!\n');
  console.log('   Login:    alex.kumar@demo.privex');
  console.log('   Password: demo1234\n');

  await prisma.$disconnect();
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  prisma.$disconnect();
  process.exit(1);
});
